os: Visual Studio 2015

environment:
  DeployExtension: false
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

build_script:
  - ps: .\appveyor.ps1

nuget:
  account_feed: true
  project_feed: true

artifacts:
  - path: OutputRoot\vs\PecanWaffle*
  - path: 'OutputRoot\*.ps*1'
  - path: 'OutputRoot\_nuget-pkg\*.nupkg'
